### ISSUE TITLE
Lässt sich nicht installieren

### ISSUE THREAD

**Issue by NerxG** [neoplay/DikVARO#1]
Hey, 
Ich kann dein Plugin nicht auf meinem Minecraftserver installieren.
Spigot, Craftbukkit geht nicht.

Hab auf der Version 1.8 und 1.7.2 versucht.

Der Minecraftserver läuft auf Linux.

MfG NerxG

**Comment by neoplay** [comment]
was heisst das genau? ich brauche eine genauere beschreibung, wenn möglich inkl. vollständiger fehlermeldung.

**Comment by NerxG** [comment]
Okay, im Log erscheint diese fehlermeldung:

[12:28:32] [Server thread/ERROR]: Could not load 'plugins/DikVARO.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:290) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

**Comment by neoplay** [comment]
Bitte lade mal die aktualisierte Version herunter, habe sie gerade nochmals ausgetauscht:
https://github.com/neoplay/DikVARO/releases/download/0.9/DikVARO.jar
